# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_path',
            field=models.ImageField(default='profile_pics/prof.jpg', upload_to='media/'),
        ),
    ]
