# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20200209_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(default='avechi', max_length=140),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='photos/dance.jpg', upload_to='photos/'),
        ),
    ]
