# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20200210_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='photos/dance.jpg', upload_to='images/'),
        ),
    ]
